apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-guard
  namespace: kube-guard
  labels:
    app: kube-guard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-guard
  template:
    metadata:
      labels:
        app: kube-guard
    spec:
      serviceAccountName: kube-guard
      containers:
      - name: kube-guard
        image: kube-guard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: webhook
        env:
        - name: CONFIG_MAP_NAME
          value: "kube-guard-config"
        - name: CONFIG_MAP_NAMESPACE
          value: "kube-guard"
        - name: PORT
          value: "8443"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000